### PR TITLE
add support for +p python integration

### LINKED ISSUE #10: Add support for python `+p`
In https://github.com/cross-language-cpp/djinni-generator/pull/43 python support is proposed and will likely come into master as an experimental feature in the next months.

As a user I'd like the vscode extension to support interfaces that marked for implementation in python (`+p`)

### PR DESCRIPTION
**Pull request by jothepro**
fixes #10

### CODE REVIEW

**Review by freitass — APPROVED** [review]
Looks good! 👍 I have only one comment...

At the risk of being too picky, I'm not 100% sure where to put a description when tagging a new release. (I assume it's a matter of creating an annotated Git tag.)

**Review by a4z — APPROVED** [review]
Super nice!

**Comment by jothepro** [comment]
@freitass I've added a link to the github documentation on how to create a release. Hope this makes things clearer.
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by freitass** [comment]
Awesome! I learnt something new 😁

**Pull request merged**
